### ISSUE TITLE
can't find shots to update

### ISSUE THREAD

**Issue by willDTF** [austinwitherspoon/resolve-version-up-shots#1]
hello, 
thanks for this script, it's looks perfect for quick update, but sadly i'm not able to make it work
i tried your script on resolve 18.1 / win11 (python 3.6.8) 
the window open normally, but when i "scan for latest version", nothing appear in Shots table

In my timeline, I have a shot in v01,
![image](https://user-images.githubusercontent.com/4272733/214815555-01bdc934-6889-4580-87a5-4f05d4ea1a9e.png)

and all versions in same folder/format
![image](https://user-images.githubusercontent.com/4272733/214815298-6230dc53-e9c7-4b52-92ca-334f0799830e.png)

I have tried both "all tracks" and the specific one i want, nothing happened
No message appear in resolve console to snitch what the problem is, any idea please ? 
thanks

**Comment by austinwitherspoon** [comment]
It looks like there was an error with .mov files (I had previously only tested on .exr and .dpx image sequences!) and how it was reading the version numbers on those .mov files.

This is fixed now for me, you should be able to download the newest update and hopefully things work for you!

**Comment by willDTF** [comment]
thanks, it can found version now but it's not able to import the new one, it show this error message 
![image](https://user-images.githubusercontent.com/4272733/215086224-58421eb3-1e13-405e-b7b9-0b845654cb83.png)

here is console feedback

`Scanning Versions..
Timeline: IN_remaster_v40
Target Track: Video 5
Scanning track 5 (Video 5)
Found 1 clips
Scanning Sq002_P0015_v03.mov
Creating new shot object for Sq002_P0015_v03.mov
Path: \\192.168.1.52\Projects_b\0104_CrossTheAges_Trailer_2022-06-14_william\Media\Anim_remaster\SQ02\Sq002_P0015_v03.mov
Extracted version from clip: ['v03']
Scanning Sq002_P0015_v03.mov.. version: v03.
	Glob: \\192.168.1.52\Projects_b\0104_CrossTheAges_Trailer_2022-06-14_william\Media\Anim_remaster\SQ02\Sq002_P0015_*.mov
	Frame Range: []
Glob: \\192.168.1.52\Projects_b\0104_CrossTheAges_Trailer_2022-06-14_william\Media\Anim_remaster\SQ02\Sq002_P0015_*.mov
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python\Python36\lib\logging\__init__.py", line 994, in emit
    msg = self.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 840, in format
    return fmt.format(record)
  File "C:\Python\Python36\lib\logging\__init__.py", line 577, in format
    record.message = record.getMessage()
  File "C:\Python\Python36\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Edit\Version Up Shots.py", line 483, in <module>
    VersionUpShots()
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Edit\Version Up Shots.py", line 91, in __init__
    self.dispatcher.RunLoop()
  File "<nofile>", line 167, in RunLoop
  File "<nofile>", line 123, in Dispatch
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Edit\Version Up Shots.py", line 218, in scanVersions
    shot = Shot(clip)
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Edit\Version Up Shots.py", line 325, in __init__
    available = self.availableVersions()
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Edit\Version Up Shots.py", line 349, in availableVersions
    logger.debug("is sequence?", isSequence)
Message: 'is sequence?'
Arguments: (False,)
results:
['v03', 'v06']
Building shot list..
Done!`

**Comment by austinwitherspoon** [comment]
I've been experimenting a bit, and it appears this issue is that resolve's API doesn't know how to handle UNC paths.

You can import from `\\192.168.1.52\` manually and it works fine, but when I try to do it from the API it fails.

I'll experiment some more, but I'm not having any luck and this may be an issue with Resolve itself. I'll send in a bug report!


In the meantime, you can fix the issue by mounting the network location to your computer as a letter drive.
Go to windows explorer and "Map a Network Drive" 

![image](https://user-images.githubusercontent.com/46503991/215164279-1458c6cc-26d9-47bd-ae94-a11d43180388.png)

And then enter your network path and choose a drive letter.
![image](https://user-images.githubusercontent.com/46503991/215164341-d0eb1a33-f802-4a89-9ccb-df84bf4e378d.png)


If you use this letter drive in resolve instead of the UNC network path, everything should hopefully work for you!

**Comment by willDTF** [comment]
thanks, didn't thinked to check without UNC, works perfectly !
